[package]
name = "runiq_ahash"
version = "1.2.3" # remember to update html_root_url
authors = ["Isaac Whitfield <iw@whitfin.io>"]
description = "An efficient way to filter duplicate lines from input, à la uniq."
repository = "https://github.com/whitfin/runiq"
keywords = ["filtering", "logging", "unique"]
categories = ["algorithms", "command-line-utilities", "text-processing"]
readme = "README.md"
edition = "2018"
license = "MIT"

[badges]
travis-ci = { repository = "whitfin/runiq" }

[dependencies]
bytelines = "2.4"
clap = { version = "3.1", features = ["derive"] }
fnv = "1.0"
scalable_bloom_filter = "0.1"
ahash = "0.8.3"

